exclude: |
  (?x)^(
    docs/conf.py
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: pretty-format-json
        args: ["--autofix", "--indent=2", "--no-sort-keys"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      args:
        - --line-length=150
        - --exclude= B950


  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black
        exclude: .git,__pycache__,build,dist
        args:
          - --max-line-length=150
          - --extend-ignore= E203, E266 BLK100, F811
        #F811 flags selective_stack from noise_module becuase there are two modules with the same name but different parameters
        #BLK100 designates where Black would make changes
        #E266 Too many leading '#' for block comment
        #E203 Whitespace rule relating to ':' that directly conflicts with black standards
