name: Test notebook
description: Test jupyter notebook
inputs:
  python-version:
    required: true
    description: Python version to install
  notebook-path:
    required: true
    description: Path to the notebook to run
runs:
  using: composite
  steps:
    - name: Setup NoisePy
      uses: ./.github/actions/setup
      with:
        python-version: ${{matrix.python_version}}
    - uses: yaananth/run-notebook@v2
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: "{}"
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: ${{inputs.notebook-path}}
        isReport: False
        poll: False
    - name: Get HTML file name
      shell: bash
      run: |
        HTML_FILE=$(ls ${{ RUNNER.temp }}/nb-runner/*.html);export HTML_FILE
        echo "HTML_FILE is $HTML_FILE"
        echo "html_file=$HTML_FILE" >> "$GITHUB_ENV"
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{inputs.notebook-path}}.html
        path: ${{ env.html_file }}
      env:
        RUNNER: ${{ toJson(runner) }}
