name: Test notebook
description: Test jupyter notebook
inputs:
  python-version:
    required: true
    description: Python version to install
  notebook-path:
    required: true
    description: Path to the notebook to run
runs:
  using: composite
  steps:
    - name: Setup NoisePy
      uses: ./.github/actions/setup
      with:
        python-version: ${{matrix.python_version}}
    - uses: yaananth/run-notebook@v2
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: "{}"
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: ${{inputs.notebook-path}}.ipynb
        isReport: False
        poll: False
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{inputs.notebook-path}}.html
        path: ${{ RUNNER.temp }}/nb-runner/${{inputs.notebook-path}}.html
      env:
        RUNNER: ${{ toJson(runner) }}
