name: Test

on: 
  pull_request:
  push: { branches: [master] }
  workflow_dispatch:

jobs:
  unit_test:
    name: ${{ matrix.python-version }}-unit-test
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version: ['3.8'] # TODO: What over versions do we need to support?
        experimental: [false]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.3.0
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
    - name: Install project
      run: |
        python -m pip install --upgrade pip
        pip install "."